### ISSUE TITLE
No module named 'torch2trt_dynamic.converters.Conv2d'

### ISSUE THREAD

**Issue by Oswells** [grimoire/mmdetection-to-tensorrt#113]
我用docker搭建的环境，因为服务器似乎没办法git clone，所以我自己魔改了Dockerfile，遇到了这个问题。请问我可以朝哪个方向出发去解决这个问题？
```shell
import mmdet2trt 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/space/mmdetection-to-tensorrt/mmdet2trt/__init__.py", line 1, in <module>
    from .converters import *  # noqa: F401,F403
  File "/root/space/mmdetection-to-tensorrt/mmdet2trt/converters/__init__.py", line 1, in <module>
    from .anchor_generator import convert_AnchorGeneratorDynamic
  File "/root/space/mmdetection-to-tensorrt/mmdet2trt/converters/anchor_generator.py", line 1, in <module>
    from torch2trt_dynamic import get_arg, tensorrt_converter, trt_
  File "/root/space/torch2trt_dynamic/torch2trt_dynamic/__init__.py", line 3, in <module>
    from .converters import *  # noqa: F401,F403
  File "/root/space/torch2trt_dynamic/torch2trt_dynamic/converters/__init__.py", line 29, in <module>
    from .Conv2d import convert_Conv2d
ModuleNotFoundError: No module named 'torch2trt_dynamic.converters.Conv2d'
```

**Comment by Oswells** [comment]
上面的问题解决了，原因是我手动download时一些文件莫名其妙缺失了...
我遇到另一个问题：tensorrt推理第一张图速度特别慢5.01s，后面的都很快0.085s，请问这样正常吗？

**Comment by zfw-cv** [comment]
你好，你解决了么。我也发生了这个问题
