### ISSUE TITLE
WARNING:root:can't find wrap module for type:<class 'mmdet.models.backbones.resnext.ResNeXt'>, use <class 'mmdet2trt.models.backbones.base_backbone.BaseBackboneWraper'> instead.

### ISSUE THREAD

**Issue by Wulingtian** [grimoire/mmdetection-to-tensorrt#53]
WARNING:root:can't find wrap module for type:<class 'mmdet.models.backbones.resnext.ResNeXt'>, use <class 'mmdet2trt.models.backbones.base_backbone.BaseBackboneWraper'> instead.
[TensorRT] ERROR: Parameter check failed at: ../builder/Layers.cpp::TopKLayer::3499, condition: k > 0 && k <= MAX_TOPK_K
[TensorRT] INTERNAL ERROR: Assertion failed: mParams.k > 0
../builder/Layers.cpp:3534
Aborting...
Traceback (most recent call last):
  File "to_trt_model.py", line 32, in <module>
    trt_model = mmdet2trt(cfg_path, weight_path, opt_shape_param=opt_shape_param, fp16_mode=True, max_workspace_size=max_workspace_size)
  File "/home/willer/tianchi/mmd_solution/mmdetection-to-tensorrt/mmdet2trt/mmdet2trt.py", line 147, in mmdet2trt
    int8_calib_algorithm=int8_calib_algorithm)
  File "/home/willer/tianchi/mmd_solution/torch2trt_dynamic/torch2trt_dynamic/torch2trt_dynamic.py", line 513, in torch2trt_dynamic
    outputs = module(*inputs)
  File "/home/willer/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/willer/tianchi/mmd_solution/mmdetection-to-tensorrt/mmdet2trt/models/detectors/single_stage.py", line 49, in forward
    result = bbox_head(feat, x)
  File "/home/willer/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/willer/tianchi/mmd_solution/mmdetection-to-tensorrt/mmdet2trt/models/dense_heads/gfl_head.py", line 79, in forward
    scores = mm2trt_util.gather_topk(scores, 1, topk_inds)
  File "/home/willer/tianchi/mmd_solution/mmdetection-to-tensorrt/mmdet2trt/ops/util_ops.py", line 50, in gather_topk
    num_index = len(index.shape)
  File "/home/willer/tianchi/mmd_solution/torch2trt_dynamic/torch2trt_dynamic/shape_converter.py", line 11, in new_getattribute__
    return get_tensor_shape(self)
  File "/home/willer/tianchi/mmd_solution/torch2trt_dynamic/torch2trt_dynamic/shape_converter.py", line 5, in get_tensor_shape
    return self.size()
  File "/home/willer/tianchi/mmd_solution/torch2trt_dynamic/torch2trt_dynamic/torch2trt_dynamic.py", line 307, in wrapper
    converter['converter'](ctx)
  File "/home/willer/tianchi/mmd_solution/torch2trt_dynamic/torch2trt_dynamic/converters/size.py", line 36, in convert_size
    input_trt = trt_(ctx.network, input)
  File "/home/willer/tianchi/mmd_solution/torch2trt_dynamic/torch2trt_dynamic/torch2trt_dynamic.py", line 144, in trt_
    num_dim = len(t._trt.shape)
RuntimeError: std::exception

**Comment by grimoire** [comment]
Hi,
Could you please provide the config of your model?

**Comment by Wulingtian** [comment]
> Hi,
> Could you please provide the config of your model?
您好，邮箱发你了(正在打比赛，不方便公开)

**Comment by scuizhibin** [comment]
你好，这个问题你是怎么解决的？
