### ISSUE TITLE
Can't import mmdet2trt on jetson

### ISSUE THREAD

**Issue by O2andsAnoxia** [grimoire/mmdetection-to-tensorrt#61]
**Describe the bug**
Can't import mmdet2trt,although i had installed as guide.The error info as follew:

`import mmdet2trt

dummy converters not found.

Traceback (most recent call last):

 File "<stdin>", line 1, in <module>

 File "/home/aurora/mmdetection-to-tensorrt/mmdet2trt/__init__.py", line 3, in <module>

  from .core import * # noqa: F401,F403

 File "/home/aurora/mmdetection-to-tensorrt/mmdet2trt/core/__init__.py", line 1, in <module>

  from .anchor import * # noqa: F401,F403

 File "/home/aurora/mmdetection-to-tensorrt/mmdet2trt/core/anchor/__init__.py", line 1, in <module>

  from .anchor_generator import AnchorGeneratorWraper, SSDAnchorGeneratorWraper

 File "/home/aurora/mmdetection-to-tensorrt/mmdet2trt/core/anchor/anchor_generator.py", line 3, in <module>

  from mmdet2trt.models.builder import register_wraper

 File "/home/aurora/mmdetection-to-tensorrt/mmdet2trt/models/__init__.py", line 3, in <module>

  from .dense_heads import * # noqa: F401,F403

 File "/home/aurora/mmdetection-to-tensorrt/mmdet2trt/models/dense_heads/__init__.py", line 7, in <module>

  from .fcos_head import FCOSHeadWraper

 File "/home/aurora/mmdetection-to-tensorrt/mmdet2trt/models/dense_heads/fcos_head.py", line 3, in <module>

  import mmdet2trt.core.post_processing.batched_nms as batched_nms

AttributeError: module 'mmdet2trt' has no attribute 'core'`

**enviroment:**
 - OS: [Ubuntu18.04, Jetson AGX Xavier]
 - python_version: [3.6.11]
 - pytorch_version: [1.6.0]
 - cuda_version: [cuda-10.2]
 - cudnn_version: [8.0.0]
 - mmdetection_version: [2.11.0]

**Additional context**
I can success as same step on my PC,but the problem emerged on Jetson AGX Xavier.

**Comment by O2andsAnoxia** [comment]
I have sent a screenshots that contains the error、bashrc info and install info about this problem in QQ group.Maybe it can offer more infomation.

**Comment by O2andsAnoxia** [comment]
I had salved this problem by using another release version

**Comment by O2andsAnoxia** [comment]
> ensorR

Yes, it works done on my jetson.

**Comment by O2andsAnoxia** [comment]
> Hi! I am curious, were you able to run mmdetection models on Jetson with TensorRT?

Yes, it works done on my jetson.
