### ISSUE TITLE
ValueError: __len__() should return >= 0

### ISSUE THREAD

**Issue by Kaeseknacker** [grimoire/mmdetection-to-tensorrt#63]
**Describe the bug**
I try to convert a standard model from MMDetection, but keep running into problems:

```
python inference.py ../../mmdet2trt_runtime_test/001601.jpg ../../mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py ../../checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth ./faster_rcnn_r50_rtx3060_fp16.engine --fp16
dummy converters not found.
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] INFO: Detected 1 inputs and 4 output network tensors.
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::resolveSlots::1318, condition: allInputDimensionsSpecified(routine)
Traceback (most recent call last):
  File "inference.py", line 70, in <module>
    main()
  File "inference.py", line 40, in main
    result = inference_detector(trt_model, image_path, cfg_path, args.device)
  File "/home/user/Programme/DroneDetection/mmdetection-to-tensorrt/mmdet2trt/apis/inference.py", line 48, in inference_detector
    result = model(tensor)
  File "/home/user/miniconda3/envs/mmdet-2.10_v9/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/Programme/DroneDetection/torch2trt_dynamic/torch2trt_dynamic/torch2trt_dynamic.py", line 478, in forward
    shape = tuple(self.context.get_binding_shape(idx))
ValueError: __len__() should return >= 0
```

**enviroment:**
```
sys.platform: linux (Ubuntu18.04)
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 3060
CUDA_HOME: /home/user/lib/cuda_11.0.3_450.51.06
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.0
OpenCV: 4.5.2
MMCV: 1.2.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.10.0+bec24ea
```

**Additional context**
I've tried many different combinations of the individual components (pytorch, mmdetection, mmcv, cuda, ...) to get that far. More recent PyTorch versions (1.8.0) or older CUDA versions (< 11) e.g. do not work with my relatively new GPU (RTX 3060).

The conversion script mmdet2trt appears to be running but the usage of the trt model file doesn't work.

I would appreciate any advice.

**Comment by grimoire** [comment]
It seems that your input tensor shape does not much your conversion parameters.
Try update all repos, convert your model with CLI or python script, make sure you have right `opt_shape_param` config.

**Comment by Kaeseknacker** [comment]
The conversion seems to work, but inference doesnt work. In the example above I used your python inference.py script.

Conversion via CLI:
standard faster rcnn model from mmdetection.
I used your recommended scale values (from demo/cpp/README.md)
```
 mmdet2trt --save-engine=true --min-scale 1 3 320 320 --opt-scale 1 3 544 960 --max-scale 1 3 800 1344 ../mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py ../checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth ./faster_rcnn_r50_rtx3060.engine
dummy converters not found.
INFO:mmdet2trt:Model warmup
INFO:mmdet2trt:Converting model
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] INFO: Detected 1 inputs and 4 output network tensors.
INFO:mmdet2trt:Conversion took 37.086353063583374 s
INFO:mmdet2trt:Saving TRT model to: ./faster_rcnn_r50_rtx3060.engine
INFO:mmdet2trt:Saving TRT model engine to: faster_rcnn_r50_rtx3060.engine
```

With my inference skript I get the following error:
```
init trt model
Traceback (most recent call last):
  File "../mmdet2trt_runtime_test/inference_trt.py", line 79, in <module>
    main()
  File "../mmdet2trt_runtime_test/inference_trt.py", line 23, in main
    trt_model = init_detector(args['trt_model'])
  File "/home/user/Programme/DroneDetection/mmdetection-to-tensorrt/mmdet2trt/apis/inference.py", line 10, in init_detector
    model_trt.load_state_dict(torch.load(trt_model_path))
  File "/home/user/miniconda3/envs/mmdet-2.10_v9/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/user/miniconda3/envs/mmdet-2.10_v9/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow
```

my inference skript:
```python
import time
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter

import torch
from PIL import Image
import numpy as np

#from mmdet2trt import mmdet2trt
from mmdet2trt.apis import inference_detector, init_detector


def main():

    args = cli()

    device = args['device']

    cfg_path = args['config']

    print("------------------------")
    print("init trt model")
    start = time.time()
    trt_model = init_detector(args['trt_model'])
    end = time.time()
    print(f" took {format(end - start, '0.3f')} s")

    print("------------------------")
    print("load image")
    start = time.time()
    image_path = args['img']
    image = Image.open(image_path)
    pix = np.array(image)
    end = time.time()
    print(f" took {format(end - start, '0.3f')} s")

    print("------------------------")
    print("warm up detector")
    start = time.time()
    result = inference_detector(trt_model, pix, cfg_path, device)
    end = time.time()
    print(f" took {format(end - start, '0.3f')} s")

    print("------------------------")
    print("inference_detector")
    sum, count = 0, 0
    for i in range(0, args['rounds']):

        start = time.time()
        result = inference_detector(trt_model, pix, cfg_path, device)
        torch.cuda.synchronize(device)
        end = time.time()
        runtime = end - start
        sum += runtime
        count += 1
        print(f" took {format(runtime, '0.3f')} s")

    avg_runtime = sum / count if count > 0 else 0
    print("------------------------")
    print(f"average runtime: {format(avg_runtime, '0.3f')} s")
    print("------------------------")


def cli():
    parser = ArgumentParser(description="runtime test for mmdetection to tensorRT models",
                            formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument('--img', help='Test image file', required=True)
    parser.add_argument('--config', help='mmdet Config file', required=True)
    parser.add_argument('--trt_model', help='tensorrt model save path', required=True)
    parser.add_argument('--rounds', help='How often should the model be tested?', default=50)
    parser.add_argument('--device',
                        default='cuda:0',
                        help='Device used for inference')

    args = vars(parser.parse_args())
    return args


if __name__ == '__main__':
    main()
```

I use 
mmdetection 2.10 (just like your test environment)
torch2trt_dynamic (09. May)
amirstan_plugin (26. April)

**Comment by Kaeseknacker** [comment]
I could solve my error:
The problem was (as is so often the case) the user ;-). During the conversion, I specified `<my_file_name>.engine` as the "TRT model" output file. However, the "TRT model" output file must not end with `.engine`, becaue `mmdet2trt` always creates a second "TRT model engine" output file with .engine file ending. The file ending `.engine` is therefore reserved.

The program also points this out, but unfortunately does not report any errors:
```
INFO:mmdet2trt:Saving TRT model to: ./faster_rcnn_r50_rtx3060.engine
INFO:mmdet2trt:Saving TRT model engine to: faster_rcnn_r50_rtx3060.engine
```
A warning might be nice.

**Comment by grimoire** [comment]
Nice advice, I will add a warning in the tool.
