### ISSUE TITLE
Unable to use converted YOLOv3 model

### ISSUE THREAD

**Issue by m-nny** [grimoire/mmdetection-to-tensorrt#71]
**Describe the bug**
I'm trying to convert trained model based on yolov3 from mmdet in order to use in NVIDIA Triton inference server.
Conversion using `mmdet2trt` finished successfully, but when I try to use model using `inference_detector` it throws exception
```bash
WARNING:root:module mmdet.models.dense_heads.TransformerHead not exist.
Use load_from_local loader
[TensorRT] INFO: Some tactics do not have sufficient workspace memory to run. Increasing workspace size may increase performance, please check verbose output.
[TensorRT] INFO: Detected 1 inputs and 4 output network tensors.
[TensorRT] ERROR: Parameter check failed at: engine.cpp::setBindingDimensions::1137, condition: profileMinDims.d[i] <= dimensions.d[i]
[TensorRT] ERROR: Parameter check failed at: engine.cpp::resolveSlots::1318, condition: allInputDimensionsSpecified(routine)
Traceback (most recent call last):
  File "converter/mmdetection-to-tensorrt/demo/inference.py", line 63, in <module>
    main()
  File "converter/mmdetection-to-tensorrt/demo/inference.py", line 33, in main
    result = inference_detector(trt_model, image_path, cfg_path, args.device)
  File "/workspace/converter/mmdetection-to-tensorrt/mmdet2trt/apis/inference.py", line 48, in inference_detector
    result = model(tensor)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/converter/torch2trt_dynamic/torch2trt_dynamic/torch2trt_dynamic.py", line 478, in forward
    shape = tuple(self.context.get_binding_shape(idx))
ValueError: __len__() should return >= 0
```
`mmdetection-to-tensorrt/demo/inference.py` fails with same error message

**To Reproduce**
- Download model checkpoint and config from [here](https://drive.google.com/drive/folders/1bNbP9L17Tqcn4rgtINnk2Qn3MN_ridQk?usp=sharing)
- Run
```
python converter/mmdetection-to-tensorrt/demo/inference.py \
    test.jpg \
    yolo_cropper.py \
    yolo_cropper.pth \
    yolo_cropper.trt.pth
```

**enviroment:**
 - Host OS: Manjaro Linux
 - Dev Container: based from Docker image `nvcr.io/nvidia/tensorrt:21.06-py3`
 - python_version: 3.8.5
 - pytorch_version: 1.8.1+cu111
 - cuda_version: 11.3.1
 - cudnn_version: 8.2.1
 - mmdetection_version: 2.12.0

**Additional context**

**Comment by grimoire** [comment]
You might need to set different `opt_shape_param` when you convert your model. since the default config is for the two-stage model or retinanet-like model.
read [this](https://github.com/grimoire/mmdetection-to-tensorrt/blob/master/docs/FAQ.md#q-error-parameter-check-failed-at-enginecppsetbindingdimensions1046-condition-profilemindimsdi--dimensionsdi) for detail.

**Comment by m-nny** [comment]
Thank you, I think changing min_shape solved that problem. But now, I have problem that when I run model in Triton, it fails with message
```

**Comment by grimoire** [comment]
Errr, I do not have much experience with Triton.
According to the logs, It seems like the input tensor shape is not 32 multiples(this limit comes from mmdet). Please check if the preprocess is the same as mmdetection.

**Comment by m-nny** [comment]
Thank you for direction. It was seems like it was indeed padding problem, interestingly this problem did not occur with Faster-RCNN model.

However, now I have problem that triton just exists just with this line printed
```#assertion/workspace/converter/amirstan_plugin/src/plugin/batchedNMSPlugin/batchedNMSPlugin.cpp,132
```

Which I believe is related to `amirstan_plugin`, NVM layer in particular. Is there any way of enabling logging for that plugin in order to debug this situation?

**Comment by grimoire** [comment]
I just simply add print in code and build again.
